name: ci 
on:
  push:
    branches:
      - main
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: actions/cache@v4
        with:
          key: ${{ github.ref }}
          path: .cache
      - run: pip install mkdocs-material
      - run: pip install mkdocstrings[python]>=0.18
      - run: pip3 install mkdocs-git-revision-date-localized-plugin
      - run: pip3 install --editable .
      - working-directory: ./docs
        run: mkdocs gh-deploy --force